### ISSUE TITLE
reading logical vector with all NA returns a vector of all True

### ISSUE THREAD

**Issue by r-re** [vnmabus/rdata#37]
### Bug description summary

an R data.frame like

`tmp <- data.frame(all_na = c(NA, NA))
`
is imported as
```
{'tmp': all_na
1 True
2 True
3 True}
```

### Data file(s)

tmp <- data.frame(all_na = c(NA, NA, NA))
save(tmp, "na_test.RData")

### Expected result

should return the equivalent of a missing value.

### Actual result

```
{'tmp': all_na
1 True
2 True
3 True}
```

### Software versions

rdata version: 0.9

**Comment by vnmabus** [comment]
Please, check if that happens with the development version. For me, in the development version I obtain:
```python
{'test_all_na':    all_na
1    <NA>
2    <NA>
3    <NA>}
```

**Comment by r-re** [comment]
Thanks for the quick reply and the solution. It works as you described. Thanks again!
