### ISSUE TITLE
Using `rdata.write_rds`

### ISSUE THREAD

**Issue by elgabbas** [vnmabus/rdata#47]
### Bug description summary

I would like to use `rdata.write_rds` to save python object into rds file that can be read in R.

I get the following error
```
rdata.write_rds(file_path, data)
# Error saving results to file.rds: module 'rdata' has no attribute 'write_rds'
```
I install rdata on my virtual environment using the following R code:
```
reticulate::py_install(packages = "git+https://github.com/vnmabus/rdata.git@develop", pip = TRUE)
```

The installed package does not include the `write_rds` function.

```
reticulate::py_run_string('
import rdata
print(dir(rdata))')

['Final', 'TESTDATA_PATH', 'TYPE_CHECKING', '__annotations__', '__builtins__', '__cached__', 
'__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 
'_get_test_data_path', '_read', 'annotations', 'conversion', 'files', 'parser', 'read_rda', 'read_rds', 'testing']
```

Could you please help me to be able to use `write_rds`? Which branch I should use?

### Code to reproduce the bug

```Python
rdata.write_rds(file_path, data)
```

### Expected result

No error and exporting the data to rds file

### Actual result

The error message above

### Software versions

Windows server

**Comment by elgabbas** [comment]
I have this issue using the example data in the function help:
```
reticulate::py_run_string('
import rdata
data = ["hello", 1, 2.2, 3.3+4.4j]
rdata.write_rds("example.rds", data)')

#Error in py_run_string_impl(code, local, convert) : 
 # AttributeError: module 'rdata' has no attribute 'write_rds'
```

**Comment by vnmabus** [comment]
That functionality is not yet released. You are probably looking at the documentation of the `latest` (a.k.a. development) version. You can try installing the development version to see if it works for you.

```bash
python -m pip install git+https://github.com/vnmabus/rdata.git@develop
```

**Comment by elgabbas** [comment]
Thanks @vnmabus. This was the branch I used to install rdata. The installed module does not recognize the `write_rds`.

**Comment by vnmabus** [comment]
My fault, I didn't see that. Can you print the `rdata.__version__` string, just to be sure of what code is installed?

**Comment by elgabbas** [comment]
This is the installed version: 
```
reticulate::py_run_string('
import rdata
print(rdata.__version__)')
# 0.11.2
```
Thanks

**Comment by vnmabus** [comment]
The current develop version is `0.11.3.dev0`. Maybe you had an already installed version of the package, so `py_install` didn't install it? You can try to force a reinstall with `pip_ignore_installed=TRUE`.

**Comment by elgabbas** [comment]
Thanks @vnmabus . I re-installed the package using `pip_ignore_installed=TRUE` and now I can see the `write_rds` function.

**Comment by vnmabus** [comment]
Glad to be of help!
